const DATA_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vTQ3Fh4bxosYRMoK5zeC5wbhNw6621gqbtkDgQD_XgC9RYrSalOHFbEgGWWLU_P8DmhwhhMJvNOFpaO/pub?gid=0&single=true&output=csv';
let rows=[];let state={};const $=id=>document.getElementById(id);const clean=s=>String(s??'').trim();
function parseCSV(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++;}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>clean(v)!==''))out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);if(row.some(v=>clean(v)!==''))out.push(row)}return out}
function parseDate(v){const s=clean(v);if(!s)return null;const m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);if(m){const d=new Date(+m[3],+m[1]-1,+m[2]);return isNaN(d)?null:d}const d=new Date(s);return isNaN(d)?null:d}
function status(n){return n===0?['No Output','attention']:n<=7?['Need Attention','attention']:n<=14?['On Track','track']:['Target Hit','target']}
function weekBounds(){const now=new Date();const day=(now.getDay()+6)%7;const thisStart=new Date(now);thisStart.setHours(0,0,0,0);thisStart.setDate(now.getDate()-day);const lastStart=new Date(thisStart);lastStart.setDate(thisStart.getDate()-7);const lastEnd=new Date(thisStart);lastEnd.setMilliseconds(-1);const thisEnd=new Date(thisStart);thisEnd.setDate(thisStart.getDate()+7);return{lastStart,lastEnd,thisStart,thisEnd}}
function fmt(d){return d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function aggregate(){const{lastStart,lastEnd,thisStart,thisEnd}=weekBounds();const map=new Map();for(const r of rows){const d=parseDate(r.date);if(!d)continue;const week=d>=thisStart&&d<thisEnd?'this':d>=lastStart&&d<=lastEnd?'last':null;if(!week)continue;const name=clean(r.cb);if(!name)continue;if(!map.has(name))map.set(name,{name,last:0,this:0});map.get(name)[week]++}const data=[...map.values()];return{data,lastStart,lastEnd,thisStart,thisEnd}}
function render(){const a=aggregate();state=a;const totalThis=a.data.reduce((s,x)=>s+x.this,0),totalLast=a.data.reduce((s,x)=>s+x.last,0);$('thisWeekTotal').textContent=totalThis;$('lastWeekTotal').textContent=totalLast;$('thisWeekRange').textContent=`${fmt(a.thisStart)} – ${fmt(new Date(a.thisEnd-1))}`;$('lastWeekRange').textContent=`${fmt(a.lastStart)} – ${fmt(a.lastEnd)}`;$('weekProgress').textContent=`${fmt(a.thisStart)} – ${fmt(new Date())} • Week in Progress`;$('attentionCount').textContent=a.data.filter(x=>x.this<=7).length;$('targetCount').textContent=a.data.filter(x=>x.this>=15).length;$('updatedAt').textContent=`Updated ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;drawChart(a.data);drawTable(a.data);drawComparison(a.data)}
function drawChart(data){const sorted=[...data].sort((x,y)=>x.this-y.this||x.name.localeCompare(y.name));const max=Math.max(15,...sorted.map(x=>x.this));$('chart').innerHTML=`<div class="chart-note"><span>Lowest production first</span><span>0 = No Output • 1–7 = Need Attention</span></div><div class="bars">${sorted.map(x=>{const[label,cls]=status(x.this),h=Math.max(4,x.this/max*250);return`<div class="bar-group" title="${escapeHtml(x.name)} — ${x.this} (${label})"><div class="bar-value">${x.this}</div><div class="bar ${cls}" style="height:${h}px"></div><div class="bar-name">${escapeHtml(x.name.split('@')[0])}</div></div>`}).join('')}</div>`}
function drawTable(data){const q=clean($('searchBox').value).toLowerCase();const sorted=data.filter(x=>x.name.toLowerCase().includes(q)).sort((x,y)=>x.this-y.this||x.name.localeCompare(y.name));$('tableBody').innerHTML=sorted.map(x=>{const[label,cls]=status(x.this),delta=x.this-x.last;return`<tr class="${cls==='attention'?'attention-row':''}"><td class="cb-name">${escapeHtml(x.name)}</td><td>${x.last}</td><td><strong>${x.this}</strong></td><td class="${delta<0?'negative':delta>0?'positive':''}">${delta>0?'+':''}${delta}</td><td><span class="status ${cls}">${label}</span></td></tr>`}).join('')||'<tr><td colspan="5">No matching CBs.</td></tr>'}
function drawComparison(data){$('comparison').innerHTML=[...data].sort((a,b)=>a.this-b.this||a.name.localeCompare(b.name)).map(x=>{const d=x.this-x.last,[label,cls]=status(x.this);return`<div class="compare-card ${cls}"><div class="name">${escapeHtml(x.name)}</div><div class="compare-values"><div><small>Last week</small><strong>${x.last}</strong></div><div><small>This week</small><strong>${x.this}</strong></div></div><div class="delta ${d<0?'negative':d>0?'positive':''}">${d>0?'+':''}${d} vs last week</div><span class="status ${cls}">${label}</span></div>`}).join('')||'<div>No data found for the selected weeks.</div>'}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function extractTaskRows(matrix){const result=[];const blocks=[{cb:4,status:5,date:9},{cb:19,status:20,date:24}];for(const r of matrix.slice(1)){for(const b of blocks){const cb=clean(r[b.cb]),st=clean(r[b.status]).toLowerCase(),date=clean(r[b.date]);if(cb&&st==='submitted'&&parseDate(date))result.push({cb,date})}}return result}
async function load(){try{$('error').classList.add('hidden');$('updatedAt').textContent='Loading…';const res=await fetch(DATA_URL,{cache:'no-store'});if(!res.ok)throw new Error(`Google Sheet returned HTTP ${res.status}`);const text=await res.text();const matrix=parseCSV(text);if(matrix.length<2)throw new Error('The published sheet returned no usable rows.');rows=extractTaskRows(matrix);if(!rows.length)throw new Error('No submitted task records were found in the expected CB task columns.');render()}catch(e){$('error').textContent=`Unable to load production data: ${e.message}`;$('error').classList.remove('hidden');$('updatedAt').textContent='Data load failed';console.error(e)}}
$('refreshBtn').addEventListener('click',load);$('searchBox').addEventListener('input',()=>drawTable(state.data||[]));load();